# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: localhost

development:
  <<: *default
  database: workflow_api_development
  
test:
  <<: *default
  database: workflow_api_test

production:
  <<: *default
  database: workflow_api_production
